
// Auto-generated by AutoPilot on 28-07-2023 at 04:44:34


const express = require('express');
const router = express.Router();

// GET request to return an intro about Anakin
router.get('/Anakin', (req, res) => {
    res.send(`Anakin Skywalker, a Force-sensitive human male, was a Jedi Knight of the Galactic Republic and the Chosen One of the Force.`);
});

module.exports = router;