
// Auto-generated by AutoPilot on 28-07-2023 at 04:16:33

const express = require('express');
const router = express.Router();

// GET API to generate a description for HanSolo 
router.get('/solo', (req, res) => {
    const description = "Han Solo, also known as 'The Scoundrel' is a smuggler from Corellia who became a leader in the Alliance to Restore the Republic and an instrumental figure in the defeat of the Galactic Empire during the Galactic Civil War.";
    res.send(description);
});

module.exports = router;