
// Auto-generated by AutoPilot on 28-07-2023 at 05:34:18

const express = require('express');
const router = express.Router();

// GET api to generate a starwars joke
router.get('/swJoke', (req, res) => {
    let jokes = [
        "Why did Darth Vader go to the therapist? To get some inner peace.",
        "What did the Jedi say to the bartender? Give me a beer, I'm feeling the force.",
        "What did Yoda say when he saw a ghost? Aaaaaaaoooooooohhhhhhh!"
    ];
    let randomJoke = jokes[Math.floor(Math.random() * jokes.length)];
    res.status(200).json({ "result": randomJoke });
});

module.exports = router;