
// Auto-generated by AutoPilot on 28-07-2023 at 04:57:56

const express = require('express');
const router = express.Router();

//Route for 'darthVader'
router.get('/darthVader', (req, res) => {
    //Send the famous line "I am your father,Luke!" to the client
    res.send("I am your father,Luke!");
});

module.exports = router;